### ISSUE TITLE
How to install/buy cplex? Can u add some execution samples?

### ISSUE THREAD

**Issue by jechaviz** [hzjken/crypto-arbitrage-framework#1]
Thank you

**Comment by hzjken** [comment]
cplex studio can be found here:
https://www.ibm.com/sg-en/products/ilog-cplex-optimization-studio
Free edition has some model size limitation, it would be best to get the academic edition for student, also free but no limitation.

Usage sample is in main.py, it can be used to monitor opportunities, but I haven't done real trade execution with it yet. Feel free to try

**Comment by jechaviz** [comment]
Cplex studio academic edition isn't available anymore. Can u share your cplex version? Or change the model optimization engine for one in scipy?
