### ISSUE TITLE
Empty arbitrage path :(

### ISSUE THREAD

**Issue by zjay096** [hzjken/crypto-arbitrage-framework#4]
I get profit rate 0.0 and an   empty arbitrage path :(
-->```
 path_optimizer.py:282: RuntimeWarning: divide by zero encountered in log
  (self.vol_matrix >= self.min_trading_limit).astype(int)))
profit rate: 0.0, arbitrage path: []
```<--

**Comment by priyen** [comment]
hey @zjay096  how did you solve this?
